git:
  branch: master

wants:
  mongo: true

secrets:
  - SECRET
  - ADMIN_SECRET
  - DAILY_KEY

health:
  path: /status

env:
  PRODUCTION: true
  PORT: 3000
  CMS_URL: https://cms.hack.gt/admin/api
  
